# Generated by Django 5.0.6 on 2024-07-01 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField()),
                ('is_demo_lead', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('n_employees', models.IntegerField(blank=True, null=True)),
                ('raw_json', models.JSONField()),
                ('company_name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=20)),
                ('urn', models.IntegerField()),
                ('campaign_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('raw_json', models.JSONField()),
                ('urn', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads_employees.homelead')),
            ],
        ),
    ]
